In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
cityData = pd.read_csv("weather_data/cities.csv")
cityData.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ati,TD,2021-09-10 03:53:40,13.2154,18.3353,76.42,77,100,9.04
1,1,Rio Gallegos,AR,2021-09-10 03:53:40,-51.6226,-69.2181,33.85,80,0,3.44
2,2,Mao,ES,2021-09-10 03:53:40,39.8885,4.2658,73.96,94,0,4.61
3,3,Tanout,NE,2021-09-10 03:50:06,14.9709,8.8879,84.29,51,100,8.63
4,4,Vilhena,BR,2021-09-10 03:53:41,-12.7406,-60.1458,68.09,95,89,3.13

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [20]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = cityData[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = cityData["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Heatmap of percent humidity
locations = cityData[["Lat", "Lng"]]
humidity = cityData["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Heatmap of percent humidity
locations = cityData[["Lat", "Lng"]]
clouds = cityData["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Heatmap of percent humidity
locations = cityData[["Lat", "Lng"]]
wind = cityData["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 65
What is the maximum temperature you would like for your trip? 70

In [26]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = cityData.loc[(cityData["Max Temp"] <= max_temp) & \
                                       (cityData["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
4,4,Vilhena,BR,2021-09-10 03:53:41,-12.7406,-60.1458,68.09,95,89,3.13
8,8,Bonneville,FR,2021-09-10 03:53:42,46.0802,6.4073,66.58,76,100,3.22
13,13,Winsum,NL,2021-09-10 03:53:43,53.3300,6.5208,67.21,59,99,5.37
15,15,Requena,ES,2021-09-10 03:53:44,39.4883,-1.1004,65.71,60,92,5.14
19,19,Lyantonde,UG,2021-09-10 03:53:45,-0.4031,31.1572,65.50,83,69,2.91
34,34,Ippy,CF,2021-09-10 03:53:48,6.2679,21.2247,69.28,97,100,3.36
40,40,Nkoteng,CM,2021-09-10 03:53:50,4.5167,12.0333,68.41,99,91,3.31
47,47,Saint-Pierre,RE,2021-09-10 03:53:52,-21.3393,55.4781,69.48,57,75,3.44
48,48,Villefranche-Sur-Saone,FR,2021-09-10 03:53:52,45.9833,4.7167,66.74,81,100,2.84
49,49,La Peca,PE,2021-09-10 03:53:52,-5.6111,-78.4350,68.92,81,20,3.49

In [27]:
preferred_cities_df.count()

City_ID       105
City          105
Country       104
Date          105
Lat           105
Lng           105
Max Temp      105
Humidity      105
Cloudiness    105
Wind Speed    105
dtype: int64

In [29]:
preferredCities = preferred_cities_df.dropna()
preferredCities.count()

City_ID       104
City          104
Country       104
Date          104
Lat           104
Lng           104
Max Temp      104
Humidity      104
Cloudiness    104
Wind Speed    104
dtype: int64

In [30]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                      City Country  Max Temp      Lat      Lng Hotel Name
4                  Vilhena      BR     68.09 -12.7406 -60.1458
8               Bonneville      FR     66.58  46.0802   6.4073
13                  Winsum      NL     67.21  53.3300   6.5208
15                 Requena      ES     65.71  39.4883  -1.1004
19               Lyantonde      UG     65.50  -0.4031  31.1572
34                    Ippy      CF     69.28   6.2679  21.2247
40                 Nkoteng      CM     68.41   4.5167  12.0333
47            Saint-Pierre      RE     69.48 -21.3393  55.4781
48  Villefranche-Sur-Saone      FR     66.74  45.9833   4.7167
49                 La Peca      PE     68.92  -5.6111 -78.4350

In [31]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [37]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [38]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
4,Vilhena,BR,68.09,-12.7406,-60.1458,Hotel Mirage
8,Bonneville,FR,66.58,46.0802,6.4073,Hotel Bellevue
13,Winsum,NL,67.21,53.3300,6.5208,Tuinhuis
15,Requena,ES,65.71,39.4883,-1.1004,Hotel Avenida
19,Lyantonde,UG,65.50,-0.4031,31.1572,Pals Panache Splendors
34,Ippy,CF,69.28,6.2679,21.2247,
40,Nkoteng,CM,68.41,4.5167,12.0333,Résidence OOCLO-Cannelle
47,Saint-Pierre,RE,69.48,-21.3393,55.4781,Lindsey Hôtel
48,Villefranche-Sur-Saone,FR,66.74,45.9833,4.7167,Hôtel Kyriad Villefranche Sur Saone
49,La Peca,PE,68.92,-5.6111,-78.4350,Hospedaje San Miguelito

In [40]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [43]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))